name: Sync Upstream

on:
  schedule:
    - cron: '0 3 * * *'  # Todos los días a las 03:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configura Git
        run: |
          git config --global user.email "pamoyrdm@example.com"
          git config --global user.name "pamoyrdm"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/WatWowMap/Masterfile-Generator.git
          git fetch upstream
          git checkout master
          git merge upstream/master
          git push origin master
